name: Run PR Checks
on: pull_request

jobs:
  publish-database:
    name: Publish Database
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
          # cache: true
      # - run: dotnet restore --locked-mode
      # - name: Setup PowerShell module cache
      #   id: cacher
      #   uses: actions/cache@v3
      #   with:
      #     path: "~/.local/share/powershell/Modules"
      #     key: ${{ runner.os }}-SqlServer-PSScriptAnalyzer
      - name: Install required PowerShell modules
        # if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          cd YaqeenDAL
          dotnet tool install --global dotnet-ef
          dotnet ef
          dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection --Version 12.0.1
          dotnet add package Microsoft.EntityFrameworkCore --Version 7.0.9
          dotnet add package Microsoft.EntityFrameworkCore.Tools --Version 7.0.9
          dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL --Version 7.0.4
      - name: Generate Migrations
        shell: pwsh
        run: |
          cd YaqeenDAL
          dotnet ef migrations add Migration -v
          git status
